services:
  web:
    restart: unless-stopped
    build:
      context: ./app
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - 80:80
    depends_on:
      - db
      - es

  db:
    restart: unless-stopped
    build:
      context: ./db
    expose:
      - 5432
    env_file:
      - .env.db

  es:
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node