services:
  web:
    restart: unless-stopped
    build:
      context: ./app
    env_file:
      - .env.dev
    ports:
      - 80:80
    depends_on:
      - db
      - es

  db:
    restart: unless-stopped
    build:
      context: ./db
    env_file:
      - .env.db

  es:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node